name: "ci-cd file"
on:
  push
jobs:
  lint:
    name: "launch lint first"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v3
      - name: "install modules"
        run : yarn
      - name: "run lint"
        run: yarn lint
  test:
    name: "test run"
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v5
      - name: "install modules"
        run : yarn
      - run: echo "we are going to start with the test couverage by:${{github.actor}} on ${{github.ref}}"
      - name: "run test"
        run: yarn test

