name: "ci-cd file"
on:
  push
jobs:
  lint:
    name: "launch lint first"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./shopping-list
    steps:
      - uses: actions/setup-node@v3
      - name: "install modules"
        run : yarn
      - name: "run lint"
        run: yarn lint
  test:
    defaults:
      run:
        working-directory: ./shopping-list
    name: "test run"
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: "run test"
        run: yarn test

